import type { Metadata } from 'next'
import Card from '@/components/Card'

export const metadata: Metadata = { title: 'Terms' }

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-16">
      <h1 className="text-3xl font-semibold text-gray-900 mb-2">Terms of Service</h1>
      <p className="text-gray-500 mb-10">Last updated: May 2026</p>

      <Card padding="lg" className="space-y-8">
        {[
          {
            title: 'Use of the service',
            body: 'Board of Five is a decision support tool. It is intended to help you gather and synthesise structured advice from trusted people. It is not a substitute for professional legal, financial, medical or employment advice.',
          },
          {
            title: 'Your responsibilities',
            body: 'You are responsible for the decisions you make. The advice collected through Board of Five and the AI-generated decision brief are inputs to your judgement, not instructions. You should always apply your own judgement and seek professional advice where appropriate.',
          },
          {
            title: 'Adviser invitation links',
            body: 'You are responsible for sharing invitation links only with your intended advisers. Do not post invitation links publicly. You are responsible for the security of your shared links.',
          },
          {
            title: 'AI-generated content',
            body: 'The decision brief is generated by an AI model based on the context and responses you provide. We do not guarantee the accuracy, completeness or appropriateness of AI-generated content. It should be treated as one input among many.',
          },
          {
            title: 'No professional advice',
            body: 'Nothing on Board of Five constitutes legal, financial, medical, employment or regulatory advice. If your decision involves these areas, consult a qualified professional.',
          },
          {
            title: 'Account security',
            body: 'You are responsible for maintaining the security of your account. We use email magic links for authentication. Do not forward magic link emails to others.',
          },
          {
            title: 'Service availability',
            body: 'We aim to provide a reliable service but do not guarantee uninterrupted availability. We may update, modify or discontinue features with or without notice during the MVP period.',
          },
        ].map((section) => (
          <div key={section.title}>
            <h2 className="font-semibold text-gray-900 mb-2">{section.title}</h2>
            <p className="text-gray-600 text-sm leading-relaxed">{section.body}</p>
          </div>
        ))}
      </Card>
    </div>
  )
}
